# Generated by Django 4.0.5 on 2022-06-22 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('coordinates', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'location',
            },
        ),
        migrations.CreateModel(
            name='User_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Users')),
                ('image', models.URLField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingAvg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('ratingQuantity', models.IntegerField(blank=True, null=True)),
                ('startDates', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('maxGroupSize', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('difficulty', 'difficulty'), ('easy', 'easy'), ('medium', 'medium')], max_length=10)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('coverImage', models.FileField(blank=True, null=True, upload_to='Image')),
                ('location', models.JSONField(blank=True, null=True)),
                ('startLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.location')),
            ],
            options={
                'verbose_name_plural': 'tour',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.SlugField(blank=True, max_length=200, null=True)),
                ('user', models.EmailField(blank=True, max_length=254, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('time_posted', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('tour', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
            options={
                'verbose_name_plural': 'images',
            },
        ),
    ]
