# Generated by Django 4.0.5 on 2022-06-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.FileField(upload_to='tours_img/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='coverImage',
            field=models.FileField(blank=True, null=True, upload_to='cover_img/'),
        ),
    ]
