# Generated by Django 4.0.5 on 2022-06-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_images_images_alter_tour_coverimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_img',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
