# Generated by Django 4.0.5 on 2022-06-30 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_review_user_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Image',
        ),
    ]
