# Generated by Django 4.0.5 on 2022-06-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_delete_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='tour_guide/')),
                ('creadAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
