# Generated by Django 4.0.5 on 2022-07-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tour_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked_Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=500, null=True)),
                ('tour_slug', models.SlugField()),
            ],
            options={
                'unique_together': {('user_email', 'tour_slug')},
            },
        ),
    ]
